### ISSUE TITLE
The icons folder conflicts with the default apache alias

### ISSUE THREAD

**Issue by anjinkristou** [MrBertie/taskpaperplus#1]
The icons folder conflicts with the default apache alias. I would recommend to change the name to images or something else.

**Comment by MrBertie** [comment]
I'm running 3 default Apache servers with Taskpaper and have never heard of
or had this problem.  Allow me to do some research before I begin changing
my folder names or source code, and I'll get back to you.

**Comment by MrBertie** [comment]
Is this the problem you are having?

---

[Apache and icons directory](http://www.electrictoolbox.com/apache-icons-directory/)
Posted March 28th, 2010 in Apache

Default installations of Apache usually alias /icons to Apache's icons directory which cannot be overridden in an .htaccess file. **If you do not control the Apache configuration of a server, and for maximum compatibility, it is always best to never have an /icons directory at a website's root level.**

Example default configuration

On a Debian box, for example, the following is defined at /etc/apache2/mods-available/alias.conf:
 Alias /icons/ "/usr/share/apache2/icons/"

If you control the server you could easily enough disable this alias, or change it to something else. The alias directive cannot be changed in a .htaccess file so if you do not control the server you will not be able to change it.

As I mentioned in the opening paragraph it's better for compatibility purposes to assume you can never change this so if you have to move your website to another server you don't have issues.

The solution

I ran into this issue the other day when I decided on a new website to put the icons I was using for some admin pages into a directory called /icons at the website's root level. Of course, I ended up without the icons displaying and a bunch of 404 errors in my log file like this:
 File does not exist: /usr/share/apache2/icons/myicon.png

The best solution is to either put your icons directory into a subdirectory, or give it a different name if it's at the root level. In my case I moved it so it was a subdirectory of /images.

---

From what I can see are you using Taskpaperplus in the web root folder.  I always run it in a separate _Taskpaper_ subfolder, so have never experienced this problem.

What are your thoughts?

Symon

**Comment by anjinkristou** [comment]
Yes, I faced this problem when I deployed the app on my apache2 on Ubuntu 10.11

**Comment by anjinkristou** [comment]
I think it would be better to change the name of the folder as it is similar to default one. The change will not cost a regression I think.
These were my two cents.

**Comment by MrBertie** [comment]
const and regression?

**Comment by anjinkristou** [comment]
Sorry. I wanted to say. It will not cost a regression.

**Comment by MrBertie** [comment]
Okay, I shall see what I can do... watch for a new GitHub push in the
coming days

Symon

**Comment by anjinkristou** [comment]
Thank you. 
—

**Comment by MrBertie** [comment]
Done!

**Comment by anjinkristou** [comment]
Thank you very much. Keep the great work.

**Comment by MrBertie** [comment]
You are welcome. There is an updated help  file too explaining how to use
the program.
Symon
