### ISSUE TITLE
“Intelligent” creation of new topics

### ISSUE THREAD

**Issue by J5lx** [MrBertie/taskpaperplus#11]
Currently when I create a new task like “foo: bar” using the search field, taskpaper+ creates a new task called “foo: bar”. However it would be useful to detect the colon and automatically create a new topic called “foo” containing a new task called “bar” instead. It would be really great if this feature could be added.

**Comment by MrBertie** [comment]
Sounds reasonable, I'll have a look when I get a moment.

**Comment by MrBertie** [comment]
Okay I have this working, I'll try to push the changes this weekend.

**Comment by j5lx** [comment]
Cool!

**Comment by MrBertie** [comment]
Done.

**Comment by j5lx** [comment]
Great!
