### ISSUE TITLE
Semicolon kill rest of the page

### ISSUE THREAD

**Issue by pchala** [MrBertie/taskpaperplus#12]
if you submit something like:

blabla
:
blabla1

blabla1 will disappear

v 1.3.0

**Comment by MrBertie** [comment]
The don't put a colon then ;-)  No, seriously I'll take a look and see if I
can find the cause.  Thanks for reporting it.

**Comment by j5lx** [comment]
I can confirm that. Furthermore the contents behind the colon will not just disappear but also get completely lost (as I painfully had to acknowledge).

**Comment by MrBertie** [comment]
This has been fixed in the latest release.  Sorry for any frustration!
