### ISSUE TITLE
can not start taskpaperplus local on Windows 7

### ISSUE THREAD

**Issue by ghost** [MrBertie/taskpaperplus#3]
In your wiki you've wrote that the uploaded version contains a Micro-Apache. Unfortunately I could not find the folder.

**Comment by MrBertie** [comment]
Yes, I need to update that!  Micro-Apache is no longer supported by its
author, and I've started using Nginx instead.  There is a version on-line
in my taskpaperplus-server repository, but it has a couple of bugs I need
to fix.  Be patient and I'll inform you once it is working properly again.

Symon

**Comment by ghost** [comment]
Ok, thanks

Am Freitag, 21. Juni 2013 schrieb MrBertie :

**Comment by MrBertie** [comment]
You can now try the [stand-alone version](https://github.com/MrBertie/taskpaperplus-server) of Taskpaper+, it works well enough on my test machine.
Thanks.
