### ISSUE TITLE
Doesn't Work!

### ISSUE THREAD

**Issue by rickydeez** [MrBertie/taskpaperplus#5]
I uploaded all files and when I load up the site, all I get is the Login page.

Filling out the login and register does nothing.

**Comment by carlos-andres** [comment]
Good Day, 
i got a centos machine and apache and php 5.4, and i try to using it on uniserver too, i access to login/create users, but not work.  search to the log i get nothing relevant, i thing missing information or configuration setting.

::1 - - [10/Jan/2014:11:31:31 -0500] "GET /taskpaper/ HTTP/1.1" 200 749 "-" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36"
::1 - - [10/Jan/2014:11:31:50 -0500] "POST /taskpaper/index.php HTTP/1.1" 200 749 "http://localhost:88/taskpaper/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36"

**Comment by MrBertie** [comment]
I don't know the cause, but I  am working on it.  Sorry for the frustration!

**Comment by MrBertie** [comment]
I just pushed a new version; it works fine on my machine, but it could an environment issue.  I'll try it on another machine next week.

**Comment by MrBertie** [comment]
The latest push should fix this problem.  I've tested on both my machines with a freshly download version and it works fine now.

**Comment by carlos-andres** [comment]
Many Thanks it works perfectly!..

**Comment by MrBertie** [comment]
Great, it was s simple matter once I found the problem: some browsers do
not return URL args that do not have a value... hence it worked for me but
not for others.
